### ISSUE TITLE
Implement email service

### ISSUE THREAD

**Issue by amirhessampourhossein** [thisisnabi/Blogger#12]
Hi @thisisnabi ,
Before anything, I want to thank you for your great repository.❤️ It's brilliant and I am learning a lot from it. 👍

I noticed the email service is not implemented and I would to like to develop this feature.
There are two main subjects that need to be discussed :

- The **email address**  that we are going to send **from**
- The implementation itself (I was thinking about **FluentEmail** package but we could also do it from scratch)

What are your thoughts ?

**Comment by thisisnabi** [comment]
Thanks for your Issue. I will implement it with `SmtpClient`, simple and built-in Class.

**Comment by amirhessampourhossein** [comment]
Great! and about the email address, I can add a json field in `appsettings.Development.json` I will leave it empty and you can set it later once the email address of the project is ready.

what do you think ? @thisisnabi
