### ISSUE TITLE
primary keys problem

### ISSUE THREAD

**Issue by naderjavid** [thisisnabi/Blogger#25]
Hello, This is database diagram of blogger, I think that yellow marked fields should be primary keys of particular tables. because in this situation we can have multiple record with same data
like below!!

SubscriberId   ArticleId Id
1111111111  2222222   1
1111111111  2222222   2
1111111111  2222222   3

![blog-db-diagram](https://github.com/thisisnabi/Blogger/assets/30950912/5ab4309c-f8c6-4d1d-8aa9-994f4e16ee49)

It should be something like this

![Screenshot 2024-05-08 150020](https://github.com/thisisnabi/Blogger/assets/30950912/340317e4-4988-49e8-bca2-e77969cc3696)

Or something like that

![Screenshot 2024-05-08 150236](https://github.com/thisisnabi/Blogger/assets/30950912/2dd58aaa-2d53-43a6-ba67-a5f5f83ab06a)

**Comment by thisisnabi** [comment]
I will check it Nader, thanks

**Comment by thisisnabi** [comment]
It's a composite key be defined as a combination of multiple columns. it's correct.
