### ISSUE TITLE
Emit Domain Event to leverage SRP and OCP

### ISSUE THREAD

**Issue by rezataroosheh** [thisisnabi/Blogger#37]
As a suggestion, emitting a domain event like CommentCreated would be more effective when creating a comment. A handler, such as the MakeCommentCommandHandler, can then manage this event and attempt to send the email. This approach helps separate these two logics, adhering to the Single Responsibility Principle (SRP) and Open/Closed Principle (OCP). It also allows for more straightforward future extensions, such as sending notifications through other channels.

**Comment by thisisnabi** [comment]
This is a good tip. thank you. I will do it soon.
